# Builds a Docker image for Octave with Jupyter Notebook.
#
# It can be found at:
#   https://quay.io/repository/numgeom/octave-notebook
#
# Authors:
# Xiangmin Jiao <xiangmin.jiao@stonybrook.edu>

FROM quay.io/numgeom/base
LABEL maintainer "Xiangmin Jiao <xiangmin.jiao@stonybrook.edu>"

# Install octave (liboctave-dev is not installed to save space.)
USER root
RUN apt-get update && \
    apt-get upgrade -y -o Dpkg::Options::="--force-confold" && \
    apt-get install -y octave gnuplot && \
    rm -rf /var/lib/apt/lists/*

# Install latex_envs for Jupyter Notebook
RUN pip3 install -U octave_kernel && \
    python3 -m octave_kernel.install

# Clean Up
RUN rm -rf /tmp/* /var/tmp/*

USER $NGUSER

# Print something nice on entry.
COPY WELCOME $NGHOME/WELCOME

USER root
